---
title: "Problem 2: HW 7 Revision"
format: html
editor: visual
embed-resources: true
author: "Jared Berghorst"
---

# Challenge 4: Price at the pump
## Making a graph to compare countries

```{python}
import pandas as pd
import altair as alt

# Loading the data
gas_prices = pd.read_csv('datasets/gas_prices.csv')

# Melting the data
gas_prices_melted = pd.melt(gas_prices, id_vars = ['country'], var_name = 'year', value_name = 'gas_price')

# Changing gas price format to numeric
gas_prices_melted['gas_price'] = pd.to_numeric(gas_prices_melted['gas_price'], errors='coerce')

# Interpolating gas price values to remove null values
gas_prices_melted['gas_price'] = gas_prices_melted.groupby('country')['gas_price'].transform(lambda x: x.interpolate())

```


```{python}
from altair import datum

alt.Chart(gas_prices_melted).mark_line().transform_filter(
  alt.FieldOneOfPredicate(field='country', oneOf=['USA', 'Saudi Arabia', 'Japan', 'UK', 'Brazil', 'China', 'Russia'])
  ).encode(
  x = 'year:O',
  y = 'gas_price:Q',
  color = 'country:N'
).properties(
    title='Gas prices in major countries are falling since 2012, with Saudi Arabia paying the least and the U.K. paying the most'
).configure_axisX(
    labelAngle=45 
)
```

The above graphic shows gas prices from 1991 to 2016 in seven selected countries. You can see that prices rose in all countries until 2012, when they began to drop. Saudi Arabia pays the least for gas, likely due to its massive oil reserves. U.K. pays the most, likely because they import nearly all of their gas and it must travel by air or sea. I chose to make a simple line graph. Most of the heavy lifting for this graphic was done in the wrangling. I melted the data to create a new column called 'year.' I also interpolated the data for each country, which essentially smoothed the gas prices between years with missing data. For the graphic, I decided to rotate the tick labels by 45 degrees to make them easier to read.

## Making a graph to compare regions

```{python}
country_info = pd.read_csv('datasets/country_info.csv')

country_info.rename(columns={'name': 'country'}, inplace=True)

# Joining the datasets
merged_data = pd.merge(gas_prices_melted, country_info, on = 'country', how = 'left')

# Calculating average gas price by region
avg_regional_gas_price = merged_data.groupby(['region', 'year'])['gas_price'].mean().reset_index()
```

```{python}
alt.Chart(avg_regional_gas_price).mark_line().encode(
  x = 'year:O',
  y = 'gas_price:Q',
  color = 'region:N'
).properties(title = 'Europe pays the most for gas, Asia pays the least. All regions have seen declining prices since 2012.').configure_axisX(
    labelAngle=45 
)
```

This graphic shows the average gas price in each world region over time. The prices overall follow a very similar trend to the previous graphic. Europe pays the most per gallon, while Asia pays the least, likely due to the close access of Middle Eastern oil reserves to the rest of Asia. I joined the two datasets in order to get the regional data, then I aggregated by region and took the mean gas price. 
